### ISSUE TITLE
Utterly Stumped

### ISSUE THREAD

**Issue by ryanbaldwin** [DaveWM/reagent-material-ui#2]
Hey man. So I'm trying to get this going in my project and I'm confused as to what's going on. Here's a quick run down:

I generated a new project using the luminus template:

```
$ lein new luminus myapp +cljs +postgres +sassc
```

I then included your jar in my project.clj

```
:dependencies
  ...[snipped for brevity]...
  [reagent-material-ui "0.2.0-SNAPSHOT"]]
```

In the `/src/cljs/myapp/core.cljs` I then added the reagent-material-ui requirement:

```
(ns myapp.core
  (:require [reagent.core :as r]
    ...[snipped for brevity]...
    [reagent-material-ui.core :as mui])
```

Finally, I modified the myapp.core/home-page function to simply try and load up the AppBar

```
(defn home-page []
  [mui/AppBar {:title "Golden Fart Nuggets Inc." :zDepth 0}])
```

I figured "hey, that should be an easy launch point" and then I can start buggering around with these sweet looking Material UI React components. However, when I fire up the app (doing a _lein run_ from the terminal) I get the following in the browser console:

```
react.inc.js:18472 Uncaught Error: Invariant Violation: AppBar.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

It's been a while since I've hacked anything up because I've been travelling for a few months, but is there anything else I need to do that's not listed in the README? I've also tried brining in the `material.js` file via a script tag, though that didn't help at all either. I'm very confused - can you help point me in the right direction?

Thanks.

**Comment by ryanbaldwin** [comment]
I determined what's going on: typical PEBCAC. I failed to realize since my travels started that reagent had been bumped to 0.5.0, and that it now automagically includes ReactJS. After excluding `cljsjs/react` from reagent's dependencies all is good in the hood. My apologies for any disruptions of what would have been an otherwise fine weekend.

Hugs and kisses.

**Comment by DaveWM** [comment]
No worries :)
