### ISSUE TITLE
No AppCanvas

### ISSUE THREAD

**Issue by ryanbaldwin** [DaveWM/reagent-material-ui#3]
Hey man. I noticed that your macros.clj doesn't include AppCanvas. Is it deprecated? Just wondering why it was left behind; I still see lots of [old] examples that use it and am confused as to whether or not it's still required.

**Comment by DaveWM** [comment]
Hey @ryanbaldwin, could you send me a link to an example? I can't see AppCanvas in the material ui docs, and it's in a folder called "internal" in their repo. What does it do exactly?

**Comment by ryanbaldwin** [comment]
I actually have no idea what it does, exactly. But if you take a look at
their included example (which is actually out of date, by the looks of
things... or so I figure) you'll notice they wrap the whole thing in an
AppCanvas. My gut would be that it sets padding and such, but I don't know.
Like I said, I have no idea if it's actually necessary or not (I'm pretty
fresh to Material).
- ryan.

**Comment by DaveWM** [comment]
Sounds like it's probably been deprecated, can you try just using a `div` element instead? If you find that AppCanvas is actually useful for something, I'll add it into the macro :)
