### ISSUE TITLE
Mui not exported?

### ISSUE THREAD

**Issue by ghost** [DaveWM/reagent-material-ui#4]
Hey there. I'm trying to consume your exposed namespace, but for some reason I'm unable to to so. Looking here:

``` clojure
(def MuiThemeProvider (-> js/MaterialUIStyles
                          (aget "MuiThemeProvider")
                          (reagent.core/adapt-react-class)))
```

I would expect MuiThemeProvider to be available if I were to `(require [reagent-material-ui.core :as mui])`. I just cannot seem to find it, however. I've been digging around this repo as well as https://github.com/cljsjs/packages/tree/master/material-ui trying to figure out who is pulling in what.

Perhaps the issue is related to a silly mistake I'm making elsewhere... It looks like material-ui has its own React (per that build dependency), so I make sure to add `[reagent "0.6.0-alpha" :exclusions [cljsjs/react]]`. However, this leads to issues when bootstrapping reagent: `Asset failed - React`... which does not make sense to me.  I'm trying to figure out if this is a separate issue or a red herring. Any suggestions would be much appreciated.

**Comment by vk-** [comment]
Hey @aft-luke, were you able to resolve the issue?
I'm able to require and use MuiThemeProvider, so the issue you're having is probably unrelated.

**Comment by ghost** [comment]
Hi vk. I actually just switched away from this lib to react-toolbox, so no I didn't resolve it. I'll close this regardless, though, since I don't have time currently to actively debug.
