### ISSUE TITLE
Minimal example usage?

### ISSUE THREAD

**Issue by habamax** [DaveWM/reagent-material-ui#5]
Hi, I am trying to use the library but the lack of initial information makes it quite challenging.

Could you share a minimum example? Simple page with AppBar or Card?

At the moment I am stuck with:

```
react.inc.js:18472 Uncaught Error: Invariant Violation: AppBar.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

With the following cljs:

```
(ns haba-dq.core
  (:require
   [reagent.core :as r]
   [reagent-material-ui.core :as mui :refer [AppBar Card Slider]]))

;; enable cljs to print to the JS console of the browser
(enable-console-print!)

(defn haba-dq-app []
  [AppBar])


(defn ^:export main []
  (r/render [haba-dq-app]
            (js/document.getElementById "app")))


;; initialize the HTML page in unobtrusive way
(set! (.-onload js/window) main)
```

**Comment by vk-** [comment]
@habamax I had the same `Invariant Violation` problem. It seems that this is because the react.js dependency is being pulled in twice, once by `reagent-material-ui` and once by reagent itself.
Excluding react `[reagent "0.6.0-rc" :exclusions [cljsjs/react]]` in my project.clj fixed it for me.

**Comment by habamax** [comment]
@vk- thx a lot! Now it works.

**Comment by habamax** [comment]
@vk- do you know why there is a warning like:

Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

When I use reagent alone I don't get this message

**Comment by vk-** [comment]
@habamax I'm not sure, if you're on `0.2.2`, you could try switching to `0.2.1`. That's the version I'm still on. Keep in mind that `0.2.1` pulls in material-ui version `0.14.4`,
So you'll need to look at docs for that [version.](http://www.material-ui.com/v0.14.4/#/components/app-bar)

**Comment by DaveWM** [comment]
@habamax I think the warning may be to do with the reagent version, in your `project.clj` do you have reagent as a dependency? If so, which version?
